version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      # VIRTUAL_ENV needs to be set manually for now; see
      # https://github.com/readthedocs/readthedocs.org/issues/11150 for details.
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs,examples --all-extras

sphinx:
  configuration: docs/source/conf.py
